### ISSUE TITLE
[기기관리] 기기정보 조회 안되는 건

### ISSUE THREAD

**Issue by complete2262** [cesco-is/cesco-air-app-new-issue#11]
**이슈에 대한 상세 설명**
실외통합대기질지수 조회 후 왼쪽 상단 기기 선택 시 장비번호가 존재하지 않는다고 나오며 흰 화면으로 전환 됨

**재현방법**
동작을 재현하는 단계:
메인화면 > 화면상단 날씨정보 클릭 > 왼쪽 상단 기기선택

**스크린 샷**
해당되는 경우 스크린 샷을 추가하여 문제를 설명하십시오.
![Screenshot_20200204-103430_bizMOB 35](https://user-images.githubusercontent.com/43739838/73714807-5c075c80-4755-11ea-8dc5-b6ef324143e7.jpg)
**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 갤럭시 팬 에디션  (android v9.0)

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by lilajung** [comment]
수정완료
