### ISSUE TITLE
[IoT 연결] 마지막 등록(장소, 특징 입력)

### ISSUE THREAD

**Issue by leeruelcg** [cesco-is/cesco-air-app-new-issue#17]
**이슈에 대한 상세 설명**
 - IoT 연결은 되어있으나 최종 단계(장소, 고객사특징) 입력 후 저장버튼 누르면 요청처리에 실패하였습니다. 문구가 뜨고 단계가 넘어가지 않는다고 함.
기기의 IoT 연결은 정상적으로 되어있음.

**재현방법**
자산번호 태깅 -> IoT 연결 -> 고객 주소 검색 -> 장소 및 특이사항 선택 -> 저장버튼 선택

**스크린 샷**

**스마트폰 (다음 정보를 작성하십시오):**
안드로이드

**추가 상황**

**Comment by melong0124** [comment]
Duplicate of #9
