### ISSUE TITLE
[스마트오토] 사용자모드 선택 시 오류문구

### ISSUE THREAD

**Issue by leeruelcg** [cesco-is/cesco-air-app-new-issue#18]
**이슈에 대한 상세 설명**
1) 풍량 : 오토
선택 : SMART -> 사용자모드 선택 시 팝업창이 조회되지 않고 [CommandCode가 없습니다.] 문구 조회 됨.

**재현방법**
동작을 재현하는 단계:
1. 운전제어 이동
2. 풍량 - AUTO / SMART -> 사용자모드 선택
3. commandCode가 없습니다. 오류문구 확인

**스크린 샷**

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 아이폰

**추가 상황**

**Comment by melong0124** [comment]
Duplicate of #26 중복으로 close 함.
