### ISSUE TITLE
꺼짐예약 중지 안됨

### ISSUE THREAD

**Issue by leeruelcg** [cesco-is/cesco-air-app-new-issue#19]
**이슈에 대한 상세 설명**
꺼짐예약 설정 후 중지버튼 누르면 중지 되지 않음.

**재현방법**
동작을 재현하는 단계:
1. 운전제어 이동
2. 꺼짐예약 설정
3. 중지버튼 클릭
4. 어플 상 오류메세지 발생 X, [잠시만 기다려주십시오] 문구 뜨고 아무 반응 없음.

**스크린 샷**

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 아이폰, 안드로이드 동일하게 발생

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by melong0124** [comment]
서버로직 수정 반영
