### ISSUE TITLE
[스마트오토] 운전제어 화면 UI 잘못 조회됨

### ISSUE THREAD

**Issue by leeruelcg** [cesco-is/cesco-air-app-new-issue#20]
**이슈에 대한 상세 설명**
운전제어 화면에서 풍량이 AUTO 가 아님에도 AUTO항목 조회됨

**재현방법**
동작을 재현하는 단계:
1. 운전제어 이동
2. 풍량 AUTO 아님 및 AUTO 항목 없는거 확인
3. 상단의 꺼짐예약 혹은 스케쥴로 이동
4. 다시 운전제어 탭으로 이동 시 AUTO 항목 조회됨

**스크린 샷**
해당되는 경우 스크린 샷을 추가하여 문제를 설명하십시오.

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 아이폰, 안드로이드
 - OS :

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by melong0124** [comment]
2/10 배포 완료 (확인)
