### ISSUE TITLE
스마트 오토 기능 팝업 오류

### ISSUE THREAD

**Issue by melong0124** [cesco-is/cesco-air-app-new-issue#26]
**이슈에 대한 상세 설명**
스마트오토 기능중 사용자 기능을 클릭하면 "commandData 가 없습니다." 오류 표출됨.

**재현방법**
동작을 재현하는 단계:
1. 기기제어 화면 이동
2. 오토 클릭
3. 스마트오토 클릭
4. 사용자 버튼 클릭

**스크린 샷**
![IMG_1457](https://user-images.githubusercontent.com/34364366/73920394-a54bdd80-4908-11ea-99f6-84be0f5b0253.PNG)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 아이폰 XS
 - OS : iOS 13.3

**Comment by yeseulLim** [comment]
- master-bugfix-26 브런치에서 수정완료.
