### ISSUE TITLE
[SMART AUTO] 파워모드 동작 안함 현상

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#28]
**이슈에 대한 상세 설명**
AUTO -> SMART 누른 후 파워모드를 누를 경우 '제어에 실패하였습니다.' 라는 메시지가 뜹니다.
 
**재현방법**
동작을 재현하는 단계:
1. 운전제어로 이동하십시오.
2. AUTO를 클릭하십시오.
3. SMART를 클릭하십시오.
4. 파워모드를 클릭하십시오.

**스크린 샷**
![Screenshot_20200207-140712_bizMOB 35](https://user-images.githubusercontent.com/43739838/74015295-ac8bed80-49d3-11ea-99b6-3943fd00ba44.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : Galaxy A50
 - OS : android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
- master-bugfix-26 브런치에서 수정 완료.
