### ISSUE TITLE
[꺼짐예약] 현재 남은 시간이 1분 단위로 감소가 안됨

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#29]
**이슈에 대한 상세 설명**
1. 꺼짐예약 시간 설정 후 현재 남은 시간이 1분 단위로 감소가 안됨
2. 일정 간격으로 화면이 깜빡 거리나 시간의 변화가 없음

**재현방법**
동작을 재현하는 단계:
1. 운전제어로 이동하십시오.
2. 꺼짐예약으로 이동하십시오
3. 꺼짐 시간을 설정하십시오.

**스크린 샷**
ex) 10분으로 설정한 경우, 시간이 지나도 현재 남은 시간 10분에서 변화 없음
![Screenshot_20200207-141345_bizMOB 35](https://user-images.githubusercontent.com/43739838/74015351-ca595280-49d3-11ea-9942-2a3acac3a4e2.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : Galaxy A50
 - OS : android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by melong0124** [comment]
서버 부분 처리 완료
