### ISSUE TITLE
[그래프 디자인] 데이터가 오른쪽 기준치(숫자)를 침범함

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#30]
**이슈에 대한 상세 설명**
실시간 데이터가 오른쪽 기준치(숫자)를 침범함

**재현방법**
동작을 재현하는 단계:
1. 데이터를 확인할 기기 1개를 클릭하십시오.

**스크린 샷**
![Screenshot_20200207-153831_bizMOB 35](https://user-images.githubusercontent.com/43739838/74015394-e3fa9a00-49d3-11ea-82f7-69ef3b374a1f.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
- 기기 : Galaxy A50
- OS : android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by melong0124** [comment]
2/10 배포 완료 (확인)

**Comment by melong0124** [comment]
@JangHW811  트랜드 쪽에 적용 되어 있지 않습니다. 적용 요청 드립니다.

**Comment by yeseulLim** [comment]
수정완료 확인
