### ISSUE TITLE
[조명] 메인 화면에서 조명 버튼 순서 변경 요청

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#31]
**이슈에 대한 상세 설명**
메인 화면의 조명 버튼을 눌렀을 때,
현재 : OFF -> 부분켜짐 -> 완전켜짐 
변경안 : OFF -> 완전켜짐 -> 부분켜짐
순서 변경
(기기와 동일하게)

**재현방법**
동작을 재현하는 단계:
1. 메인화면으로 이동하십시오.

**스크린 샷**
![Screenshot_20200207-153831_bizMOB 35](https://user-images.githubusercontent.com/43739838/74015430-f543a680-49d3-11ea-8db5-7663c2312002.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
- 기기 : Galaxy A50
- OS : android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
- 작업완료
