### ISSUE TITLE
[사용자모드] 사용자 모드에서 변경이 필요한 부분

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#33]
**이슈에 대한 상세 설명**
사용자모드에서 변경이 필요한 부분

1.  순서변경
현재 : 미세먼지 - 초미세먼지 - 극초미세먼지 - 냄새 - CO2 - 라돈
변경안 : 극초미세먼지 - 초미세먼지 - 미세먼지 - 냄새 - CO2 - 라돈
순서로 변경 필요

2. 각 센서 별 MIN, MAX 값 변경
극초미세먼지(PM1.0)  :  MIN 1,  MAX 250
초미세먼지(PM2.5) : MIN 1,  MAX 250
미세먼지(PM10) : MIN 1,  MAX 300
냄새 : 1, 2, 3, 4
CO2 : MIN 1,  MAX 5000
라돈 : MIN 0.1,  MAX 99.9

3. 실제로 기기로 설정값을 내릴 때는 극초미세먼지, 초미세먼지, 미세먼지, 라돈은 곱하기 10을 한 값으로 내림

4. 모델별로 지원되지 않는 센서는 비활성화 처리
극초미세먼지 항목 :  EP-222P 모델 외에는 모두 비활성화
라돈 항목 : EP-220P, EP-223P 모델만 비활성화
EP-223P 모델의 경우는 초미세먼지와 미세먼지만 활성화 되고 나머지는 모두 비활성화

**재현방법**
동작을 재현하는 단계:
1. 운전제어를 클릭해주세요.
2. 풍량을 AUTO로,  AUTO를 SMART로 변경해주세요.
3. 사용자모드를 클릭해주세요.

**스크린 샷**
해당되는 경우 스크린 샷을 추가하여 문제를 설명하십시오.
![Screenshot_20200207-155911_bizMOB 35](https://user-images.githubusercontent.com/43739838/74015460-0391c280-49d4-11ea-86bc-224acdfe191f.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : Galaxy A50
- OS : android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
master-20200212 버전 배포 완료
