### ISSUE TITLE
[기기관리] 장소 및 공간 변경할 때 취소 버튼 필요

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#34]
**이슈에 대한 상세 설명**
기기관리 에서장소 및 공간 변경할 때 확인 버튼 옆 취소 버튼 필요

**재현방법**
동작을 재현하는 단계:
1. 기기관리를 클릭하십시오.
2.장소 및 공간을 클릭하십시오.

**스크린 샷**
![Screenshot_20200207-160414_bizMOB 35](https://user-images.githubusercontent.com/43739838/74015498-13110b80-49d4-11ea-8073-ba28c632d9d8.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
- 기기 : Galaxy A50
- OS : android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by melong0124** [comment]
@ssook0814 UI 좀 검토좀 해주세요.

**Comment by yeseulLim** [comment]
- 정상원 완료..
