### ISSUE TITLE
[wifi 제약조건 문구 수정] 문구 수정 필요

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#35]
**이슈에 대한 상세 설명**
wifi 제약 조건 변경

- 기존 모델 (IoT 공기청정기,  IoT 공기질측정기)
     1)  SSID, PW는 한글 및 일부 특수문자의 경우 미지원
     2)  Password는 14자리 이상 미지원
     3)  고정 IP는 미지원
     4)  UDP123 시간 포트가 막혀 있을 경우 안됨
     5)  2.4 GHz만 지원
     6)  인증 및 암호화는 WPAPSK, WPA2PSK 및 TKIP, AES 방식 사용 가능

-  신규 모델 (IoT 공기청정기SE)
     1)  SSID, PW는 한글 및 일부 특수문자의 경우 미지원
     2)  2.4 GHz만 지원
     3)  인증 및 암호화는 WPAPSK, WPA2PSK 및 TKIP, AES 방식 사용 가능

**재현방법**
동작을 재현하는 단계:
1. '+' 버튼을 눌러 기기추가를 해주세요.
2. 모델을 선택해주세요.
3. 주변 기기를 검색후 다음 버튼을 눌러주세요.

**스크린 샷**
![Screenshot_20200205-090636_bizMOB 35 dev](https://user-images.githubusercontent.com/43739838/74015609-4f446c00-49d4-11ea-91e6-4213260f32d1.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : Galaxy A50
- OS : android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
- 수정완료 확인.
