### ISSUE TITLE
[에코 모드] 비정상적인 데이터가 표시됨

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#39]
**이슈에 대한 상세 설명**
운전제어 - 풍량 AUTO - SMART - 에코모드 선택시
처음에는 정상적인 값이 내려왔으나,
몇 분 정도 지나고 나면 어쩔때는 괜찮고, 어쩔때는
{ "cdate" : "2020-02-07T07:37:48.563Z", "cdatp" : "40", "cddid" : A1718361911
070018", "cdpvr" : "100", "datas" : [ { "condt" : "2020-02-07T07:37:48.563Z", "c
onid" : 1, "concd" : "C30", "valtp" : 4, "convl" : [ 300, 500, 9999, 9999, 100, 350
, 550, 9999, 9999, 150, 150, 800, 1200, 9999, 9999, 300, 300, 0, 0, 0, 0, 0, 0, 1
000, 1500, 9999, 9999, 600, 600, 20, 30, 40, 40, 10, 10, 1, 1 ] } ]}
이렇게 VOC 값들이 0인 상태로 기기로 내려왔습니다.

**재현방법**
동작을 재현하는 단계:
1. 운전제어 - 풍량 AUTO - SMART - 에코모드 클릭해주세요.

**스크린 샷**

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : [예 : 아이폰 6]
 - OS : [예 : iOS8.1]

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
- master-bugfix-26 브런치에서 수정함.
