### ISSUE TITLE
[꺼짐 예약] 꺼짐예약 중지 안됨

### ISSUE THREAD

**Issue by complete2262** [cesco-is/cesco-air-app-new-issue#4]
**이슈에 대한 상세 설명**
꺼짐예약 설정 시 중지하면 실제 예약중지는 되었으나 화면상에는 설정 당시 화면으로 보임

**재현방법**
동작을 재현하는 단계:
 - 메인 > 장비선택 > 운전제어 > 꺼짐예약

**스크린 샷**
![Screenshot_20200204-102634_bizMOB 35](https://user-images.githubusercontent.com/43739838/73714423-29a92f80-4754-11ea-90fc-62a47546f087.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 갤럭시 팬 에디션  (android v9.0)

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by melong0124** [comment]
서버 로직 반영 적용
