### ISSUE TITLE
[IoT 연결] 고정 IP 연결 방식 추가에 대한 검토 필요함

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#40]
**이슈에 대한 상세 설명**
최초 IoT 연결 시
기본으로 유동IP (DHCP) 항목으로 되어 있으나,
고객이 고정IP (STATIC IP) 연결 방식을 선택할 경우에 대한 아래 항목 추가가 필요
IP 주소,  서브넷 마스크,  게이트웨이,  기본 DNS,  보조 DNS

**재현방법**
동작을 재현하는 단계:
1. '...'로 이동하십시오.
2. '....'을 클릭하십시오.
3. '....'까지 아래로 스크롤하십시오.
4. 오류 참조

**스크린 샷**

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : [예 : 아이폰 6]
 - OS : [예 : iOS8.1]

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
- 이슈 완료
