### ISSUE TITLE
오토 모드 클릭시 하위 창의 오토가 선택이 안되있는 문제

### ISSUE THREAD

**Issue by melong0124** [cesco-is/cesco-air-app-new-issue#43]
**이슈에 대한 상세 설명**
오토 모드 클릭하면 아래의 오토가 선택이 안되어 있는 문제
(다른 화면 갔다가 돌아오면 선택 됨)
기본으로 기본 오토가 선택이 되어야 함(스마트가 아닌)

**재현방법**
동작을 재현하는 단계:
1. 제어화면 이동
2. 풍향을 오토가 아닌 것을 선택
3. 풍향을 오토로 선택
4. 오토에 선택이 안되어 있음.

**Comment by yeseulLim** [comment]
master-bugfix-43 수정.
