### ISSUE TITLE
메인화면 제어 관련 이슈

### ISSUE THREAD

**Issue by melong0124** [cesco-is/cesco-air-app-new-issue#45]
**이슈에 대한 상세 설명**
1. 메인화면에서 메뉴를 열고 기기를 다시 선택해서 풍향을 제어 하면 "controlcode 가 존재하지 않습니다." 오류 표시
2. 메인화면에 다시 진입 하면 리프레쉬가 안되는 현상
    ex) 운전제어 화면 진입 < 버튼 클릭시 (or 백버튼 클릭시)
3. 메인화면에서 풍향이 Auto 로 되어 있을 경우 버튼이 눌르지 않음.

**재현방법**
*기기 풍향제어 관련 이슈*
동작을 재현하는 단계:
1. 메인 목록에서 기기를 선택.
2. 오른쪽 상단의 메뉴 버튼 클릭
3. 기기 선택
4. 제어
5. 오류 발생 (스크린샷 참고)

*리프레쉬 이슈*
동작을 재현하는 단계:
1. 메인 목록에서 기기를 선택.
2. 운전제어 화면 이동
3. 다시 기기 화면으로 이동 (왼쪽 상단의 < 버튼 또는 back 버튼)
4. 제어관련 사항이 리프레쉬 되지 않음

*메인화면 풍향이 Auto 일 경우 이슈*
1. 메인 목록에서 기기를 선택.
2. 운전제어 화면 이동
3. 기기를 Auto 로 설정
4. 기기 메인화면으로 이동
5. 풍향 버튼 클릭
6. 작동 안되는 현상 확인

**스크린 샷**
![IMG_1507](https://user-images.githubusercontent.com/34364366/74219813-30eeb100-4cf1-11ea-958f-94b742ebeb34.PNG)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 아이폰XS
 - OS : iOS13.3.1

**Comment by yeseulLim** [comment]
- 개선완료
