### ISSUE TITLE
[사용자모드]사용자모드 값 설정 후 다른 모드 누르고, 다시 사용자모드 진입시 설정 값 저장안됨

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#46]
**이슈에 대한 상세 설명**
사용자모드 값 설정 후 다른 모드(Ex. 파워모드) 누르고, 다시 사용자모드 진입시 설정 값 저장안됨

**재현방법**
동작을 재현하는 단계:
1. 하단의 운전제어를 클릭하십시오.
2. 풍량의 오토를 클릭하십시오.
3. 스마트를 클릭하십시오.
4. 사용자모드를 클릭하십시오.
5. 사용자 설정의 값을 설정 후 확인 버튼을 클릭해주십시오.
6. 파워모드를 클릭해주십시오.
7. 다시 사용자모드를 클릭해주십시오.

**스크린 샷**
![Screenshot_20200213-093824_bizMOB 35](https://user-images.githubusercontent.com/43739838/74391188-cfd8f180-4e46-11ea-9a02-a22892495d87.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
- 기기 : Galaxy A50
- OS : Android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by lilajung** [comment]
이슈 아님
