### ISSUE TITLE
[운전제어] 특정 모델의 경우, 환기 센서 보이지 않도록 수정

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#48]
**이슈에 대한 상세 설명**
맨 하단의 환기 센서 보이지 않도록 수정
- 수정대상 
1. IoT 룸케어 공기청정기(1.0 , 1.5 , MF)
2. IoT 공기청정기(1.0)
3. IoT 라돈공기청정기(1.0)
4. IoT 라돈플러스 공기청정기(1.0)
5. IoT 라돈룸케어 공기청정기(1.0)
6. 스마트핏10
7. 스마트핏30 

**재현방법**
동작을 재현하는 단계:
1. 하단의 운전제어를 클릭하십시오.

**스크린 샷**

**스마트폰 (다음 정보를 작성하십시오):**
- 기기 : Galaxy A50
- OS : Android version 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
- 기기 상태값 받아서 환기 버튼 보여주도록 수정.(a_controlDevice.js)
