### ISSUE TITLE
세스코 에어 소개 에러

### ISSUE THREAD

**Issue by melong0124** [cesco-is/cesco-air-app-new-issue#51]
**이슈에 대한 상세 설명**
세스코 에어 소개를 터치하면 "다운로드할 수 없습니다." 에러 표시

**재현방법**
동작을 재현하는 단계:
1. 메뉴버튼 클릭
2. 마이페이지 클릭
3. 렌탈내역 탭 이동
4. 세스코 소개 클릭

**스크린 샷**
![IMG_1510](https://user-images.githubusercontent.com/34364366/74392132-86d66c80-4e49-11ea-83ca-abec23d9dc58.PNG)
![IMG_1511](https://user-images.githubusercontent.com/34364366/74392138-8938c680-4e49-11ea-91a7-9a0c4eec4495.PNG)

**Comment by yeseulLim** [comment]
cescoUtil.js : cescoUtil.downloadLeaflet() 주소 수정 및 bizmob.properties 수정
