### ISSUE TITLE
사용자모드 설정 순서, 값 변경 필요

### ISSUE THREAD

**Issue by complete2262** [cesco-is/cesco-air-app-new-issue#53]
**이슈에 대한 상세 설명**
사용자설정 센서 별 MIN, MAX 값 변경 필요.

1. 각 센서 별 MIN, MAX 값 변경
- 라돈 : MIN 0.1,  MAX 50  (라돈 MAX를 50으로 변경)
- 실제로 기기로 설정값을 내릴 때는 극초미세먼지, 초미세먼지, 미세먼지, 라돈은 곱하기 10을 한 값으로 내림

**재현방법**
동작을 재현하는 단계:
운전제어 - 풍량 - AUTO - SMART - 사용자모드 

**스크린 샷**
해당되는 경우 스크린 샷을 추가하여 문제를 설명하십시오.
![image](https://user-images.githubusercontent.com/43739838/74633435-fed3c800-51a4-11ea-8cd4-2c574316a400.png)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 갤럭시 A50
 - OS : android 9

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
- 개선 완료 배포
