### ISSUE TITLE
[제어] 장비 변경 시 제어 안되는 건

### ISSUE THREAD

**Issue by complete2262** [cesco-is/cesco-air-app-new-issue#6]
**이슈에 대한 상세 설명**
메인화면에서 장비 선택 후 상단에 다른 장비로 전환 후 기기제어 시 'Control Code가 존재하지 않습니다' 문구 뜸(제어 안됨)

**재현방법**
동작을 재현하는 단계:
메인화면 > 기기1 선택 > 화면상단에서 기기2선택 > 전원버튼 클릭

**스크린 샷**
해당되는 경우 스크린 샷을 추가하여 문제를 설명하십시오.
![Screenshot_20200204-100103_bizMOB 35](https://user-images.githubusercontent.com/43739838/73714364-02eaf900-4754-11ea-8384-9ce18155c6fd.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 갤럭시 팬 에디션  (android v9.0)

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by lilajung** [comment]
수정 완료
