### ISSUE TITLE
[스케줄] 스마트 스케줄 등록 시 공백

### ISSUE THREAD

**Issue by complete2262** [cesco-is/cesco-air-app-new-issue#7]
**이슈에 대한 상세 설명**
스케줄에 스마트오토 제어 등록 시 리스트 조회 공백으로 됨

**재현방법**
동작을 재현하는 단계:
메인 > 기기선택 > 운전제어 > 스케줄

**스크린 샷**
해당되는 경우 스크린 샷을 추가하여 문제를 설명하십시오.
![Screenshot_20200204-102537_bizMOB 35](https://user-images.githubusercontent.com/43739838/73714324-e484fd80-4753-11ea-97b6-31f5f2fe4978.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 갤럭시 팬 에디션  (android v9.0)

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by yeseulLim** [comment]
-master-bugfix0 에 수정하여 커밋.
