### ISSUE TITLE
[제어] 풍량 auto 설정 시 app,기기데이터 상이한 건

### ISSUE THREAD

**Issue by complete2262** [cesco-is/cesco-air-app-new-issue#8]
**이슈에 대한 상세 설명**
app 또는 기기 에서 풍량 1,2,3단 -> auto설정 시 app상에서 auto로 보이지않고 auto 이전 풍량으로 조회됨 (실제 기기상에서는 auto로 전환 되어있음)

**재현방법**
동작을 재현하는 단계:
메인화면 > 기기선택 > 운전제어 >풍량선택(1,2,3) > 풍량(auto)

**스크린 샷**
해당되는 경우 스크린 샷을 추가하여 문제를 설명하십시오.

![Screenshot_20200204-102040_bizMOB 35](https://user-images.githubusercontent.com/43739838/73709799-6cafd680-4745-11ea-958e-9b35bd24edf3.jpg)
![20200204_101150](https://user-images.githubusercontent.com/43739838/73714956-bbfe0300-4755-11ea-9f52-44f20bf6a143.jpg)

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : 갤럭시 팬 에디션  (android v9.0)

**추가 상황**
여기에 문제에 대한 다른 컨텍스트를 추가하십시오.

**Comment by melong0124** [comment]
서버 로직 수정 반영 완료
