### ISSUE TITLE
[기기관리] 장소 및 공간 항목 선택 사항 저장 안됨

### ISSUE THREAD

**Issue by rla01189** [cesco-is/cesco-air-app-new-issue#9]
**이슈에 대한 상세 설명**
장소와 공간을 모두 설정하고, 하단의 확인 버튼을 누르면 ‘잠시만 기다려주십시오.’ 메시지가 1초가량 빠르게 떴다 사라지고, 화면상 변화 없음

**재현방법**
동작을 재현하는 단계:
1. 하단 기기관리로 이동하십시오.
2. 장소 및 공간 항목을 클릭하십시오.
3. 설치 장소를 선택하거나 입력해주십시오.
4. 설치공간을 선택해주십시오.

**스크린 샷**

**스마트폰 (다음 정보를 작성하십시오):**
 - 기기 : Galaxy A50
 - OS : Android version 9

**추가 상황**

**Comment by rla01189** [comment]
장소와 공간을 모두 설정하고, 하단의 확인 버튼을 누르면 ‘잠시만 기다려주십시오.’ 메시지가 1초가량 빠르게 뜨며 저장 안됨

**Comment by complete2262** [comment]
![Screenshot_20200204-105842_bizMOB 35](https://user-images.githubusercontent.com/43739838/73714603-b18f3980-4754-11ea-86e4-c2239286cd36.jpg)

**Comment by lilajung** [comment]
2월 4일 처리된 건
